import { ref } from "vue";

export function useThemes() {
  const theme = ref<string>("");
  async function get() {
    const themes = [
      "La corrida",
      "Le féminisme radical",
      "Le patriarcat",
      "La Françafrique",
      "La mort thermodynamique de l'univers",
      "Le café",
      "Le thé",
      "Le cannabis",
      "Les drogues dures",
      "L'adultère",
      "Le polyamour",
      "Les impôts",
      "Manger avec les mains",
      "Se récurrer le nez",
      "Les émojis",
      "L'écologie",
      "L'avortement",
      "Chapeau, bob ou casquette ?",
      "Le travail",
      "La famille",
      "L'esclavage",
      "Le rouge et le noir",
      "Victor Hugo",
      "Adolf Hitler",
      "L'homosexualité",
      "Le terrorisme",
      "Le judaisme",
      "L'eau potable",
      "Les smartphones",
      "La décroissance",
      "Apple",
      "Les Etats-Unis d'Amérique",
      "L'Europe'",
      "La mafia",
      "Pulp fiction",
      "Nicolas Sarkozy",
      "Les ordinateurs DELL",
      "La banane",
      "Les oscars",
      "Simone de Beauvoir",
      "Suffit-il de bien travailler pour réussir ?",
      "Le bonheur",
      "L'argent",
      "La transexualité",
      "La transexualité menace-t-elle les droits des femmes ?",
      "Windows vs Apple",
      "Le metavers",
      "Les cryptomonnaies",
      "Les jeux vidéos",
      "La violence dans le cinéma",
      "L'handicap",
      "L'addiction",
      "L'antinatalisme",
      "Le but de la vie",
      "Le véganisme",
      "La sentience",
      "Albert Einstein",
      "L'énergie nucléaire",
      "L'invasion en Ukraine",
      "Le racisme anti-blancs",
      "L'orgeuil",
      "Les Fleurs du mal",
      "Les écoles d'ingénieur",
      "L'éducation positive",
      "Le SIDA",
      "Les jeux d'hiver d'Arabie Saoudite",
      "PSG ou OM ?",
      "La France, collabo ou résistante ?",
      "Le porno éthique",
      "Le porno violent",
      "Les enfants doivent-ils faire des devoirs à la maison ?",
      "L'orientation du papier toilette",
      "Les sextoys",
      "Le plaisir partagé",
      "L'excès de café",
      "La voiture",
      "Les transports en commun",
      "Les applis de rencontre",
      "Les préjugés sur les asiatiques",
      "La pizza à l'ananas",
      "L'impuissance",
      "Le don de sperme",
      "La gestation pour autrui",
      "Le cannibalisme",
      "Le titanic",
      "La pénurie de carburant",
      "La pandémie",
      "Le port du masque",
      "La vaccination obligatoire",
      "La SNCF",
      "La grève",
      "Les syndicats",
      "La peine de mort",
      "La castration chimique",
      "La reconversion professionnelle",
      "La gentrification",
      "Le skateboard",
      "Les énergies fossiles",
      "La voiture électrique",
      "Jair Bolsonaro",
      "Le mouvement Extinction Rébellion",
      "La désobéissance civile",
      "Samuel Paty",
      "#metoo",
      "Netflix",
      "La NUPES",
      "Le rap",
      "QAnon",
      "Twitter",
      "Le James Web Space Telescope",
      "L'appropriation culturelle",
      "Est-ce que les blancs peuvent porter des dreads ?",
      "Le journalisme",
      "Le Japon",
      "Les crimes de guerre Japonais",
      "Le Vatican",
      "Le voyage en avion",
      "La honte de voyager en avion",
      "L'abandon",
      "La guitare acoustique",
      "Les agriculteurs",
      "L'andouilette",
      "La putophobie",
      "Le validisme",
      "La baguette",
      "La Barbie",
      "Le cholestérol",
      "La Bible",
      "Les boissons sucrées",
      "Le caca",
      "2 girls 1 cup",
      "La musique classique",
      "L'intolérance au gluten",
      "L'astrologie",
      "La spiritualité",
      "La CIA",
      "La police tue",
      "Le consentement est-il tacite dans un couple ?",
      "Le cis-thème",
      "Les crânes rasés",
      "Les festivals de musique",
      "Les dents de sagesse",
      "Le père Noël n'existe pas",
      "Les monstres sous le lit",
      "Un marronnier",
      "Plus une personne est payée et moins son travail est important à la société",
      "La région la plus perdue de France ?",
      "Les DOM-TOMS devraient être des pays indépendants ?",
      "Est-ce que la Corse est bien Française ?",
      "La démocratie",
      "La dictature",
      "Le suffrage universel",
      "L'escrime",
      "La flemme",
      "La dépression",
      "La fourrure",
      "Les fusillades",
      "Le genre",
      "On ne naît-pas une femme, on le devient",
      "La fonte des glaces",
      "La montée des eaux",
      "Jésus a-t-il vraiment marché sur l'eau ?",
      "La majorité sexuelle",
      "Les pédophiles",
      "Le deuil",
      "Les patois",
      "La mauvaise haleine",
      "Hélène de Troie",
      "La mythologie grecque",
      "Le Hezbollah, parti politique ou organisation terroriste ?",
      "L'honnêteté radicale",
      "La sécurité sociale",
      "Le transhumanisme",
      "La salade iceberg",
      "Être ignorant rend-il plus heureux-se ?",
      "L'imagination",
      "Les mathématiques",
      "L'individualisme",
      "L'utilitarisme",
      "La tourista",
      "Quelle est la différence entre la mouette et le goéland ?",
      "Chocolatine ou pain au chocolat ?",
      "Les échecs",
      "Les laxatifs",
      "L'eugénisme peut-il être éthique ?",
      "Les religions sont-elles des sectes ?",
      "La morale",
      "La délocalisation",
      "La mondialisation",
      "Le pélerinage",
      "Les manouches",
      "Le génocide du Rwanda",
      "Mercure",
      "L'URSS",
      "Chuck Norris",
      "Les pervers narcissiques",
      "Quelle est la différence entre un néerlandais et un hollandais ?",
      "La sobriété énergétique",
      "Le sucre",
      "Les jeux olympiques",
      "La Palestine",
      "Le théâtre",
      "Le cinéma",
      "Les sports collectifs",
      "Le marathon",
      "Le patronat",
      "Les EPHAD",
      "La psychologie",
      "Les anti-dépresseurs",
      "Pétain",
      "Les pianos à queue",
      "Les pianos dans les gares",
      "Disney",
      "Star Wars ou StarTrek ?",
      "La pluralité",
      "La poésie",
      "La politique",
      "La Poste",
      "Amazon",
      "Deliveroo",
      "Le leasing",
      "Le régime keto",
      "La prostitution",
      "La virginité",
      "La discrimination positive",
      "Le sucre raffiné",
      "Le rassemblement national",
      "Le banditisme",
      "L'immunité parlementaire",
      "Le stress",
      "Les allergies",
      "La chirurgie esthétique",
      "Les saisons",
      "Les sanglots longs des violons de l'automne",
      "La bipolarité",
      "La schizophrénie",
      "La psychopathie",
      "L'éjaculation précoce",
      "Le lycée",
      "La sécheresse vaginale",
      "Le syndrome pré-menstruel",
      "les anagrammes",
      "William Shakespeare",
      "Le logiciel libre",
      "La monarchie",
      "Le BDSM",
      "Le masochisme",
      "L'escalade",
      "Le travail rend-il libre ?",
      "Les taboux",
      "La technocratie",
      "Le baccalauréat",
      "Le tourisme sexuel",
      "La tomate est-elle un fruit ou un légume ?",
      "La torture",
      "Le 69",
      "Le cancer",
      "L'utérus",
      "La contraception",
      "Les verbes du troisième groupe",
      "L'industrie de la mode",
      "Les voyages",
      "Les zombies",
    ];
    theme.value = themes[(Math.random() * themes.length) | 0];
  }

  return {
    theme,
    get,
  };
}
