import { test, expect } from '@playwright/test'

test('test super avancé', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('checkbox').click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('cell', { name: 'Nom Un castor affairé' }).getByLabel('Nom').click({
    clickCount: 3
  })
  await page.getByRole('cell', { name: 'Nom Un castor affairé' }).getByLabel('Nom').fill('Julien')
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').dblclick()
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').dblclick()
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').click({
    clickCount: 3
  })
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').fill('Oscar')
  await page.getByRole('row', { name: 'Nom Un ornithorynque' }).getByLabel('Nom').click()
  await page
    .getByRole('row', { name: 'Nom Un ornithorynque' })
    .getByLabel('Nom')
    .press('ControlOrMeta+a')
  await page.getByRole('row', { name: 'Nom Un ornithorynque' }).getByLabel('Nom').fill('Sophie')
  await page.getByRole('row', { name: 'Nom Un paresseux rêveur' }).getByLabel('Nom').click()
  await page.getByRole('row', { name: 'Nom Un paresseux rêveur' }).getByLabel('Nom').click({
    clickCount: 3
  })
  await page.getByRole('row', { name: 'Nom Un paresseux rêveur' }).getByLabel('Nom').fill('Julie')
  await page.getByRole('cell', { name: 'Nom Un koala gourmand' }).getByLabel('Nom').fill('Bob')
  await page.getByRole('cell', { name: 'Nom Un panda joueur' }).getByLabel('Nom').fill('Enzo')
  await page.getByRole('cell', { name: 'Nom Un loup solitaire' }).getByLabel('Nom').fill('Sarah')
  await page.getByRole('cell', { name: 'Nom Un renard rusé' }).getByLabel('Nom').fill('Ni')
  await page.getByRole('cell', { name: 'Nom Ni' }).getByLabel('Nom').fill('Nicolas')
  await page.getByRole('cell', { name: 'Nom Ni' }).getByLabel('Nom').press('Tab')
  await page
    .getByRole('cell', { name: 'Nom Un chat malicieux' })
    .getByLabel('Nom')
    .fill('Dieudonné')
  await page.getByLabel('Dépenseur').selectOption('1')
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('3200')
  await page.getByLabel('a dépensé').press('Tab')
  await page.getByLabel('Julien').check()
  await page.getByLabel('Julien').press('Tab')
  await page.getByLabel('Oscar').check()
  await page.getByLabel('Oscar').press('Tab')
  await page.getByLabel('Sophie').check()
  await page.getByLabel('Sophie').press('Tab')
  await page.getByLabel('Julie', { exact: true }).check()
  await page.getByLabel('Julie', { exact: true }).press('Tab')
  await page.getByLabel('Bob').check()
  await page.getByLabel('Bob').press('Tab')
  await page.getByLabel('Enzo').check()
  await page.getByLabel('Enzo').press('Tab')
  await page.getByLabel('Sarah').check()
  await page.getByLabel('Sarah').press('Tab')
  await page.getByLabel('Nicolas').check()
  await page.getByLabel('Nicolas').press('Tab')
  await page.getByLabel('Dieudonné').check()
  await page.getByLabel('Dieudonné').press('Tab')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).press('Shift+Tab')
  await page.getByLabel('Dieudonné').press('Shift+Tab')
  await page.getByLabel('Nicolas').press('Shift+Tab')
  await page.getByLabel('Sarah').uncheck()
  await page.getByLabel('Sarah').press('Shift+Tab')
  await page.getByLabel('Enzo').uncheck()
  await page.getByLabel('Dépenseur').selectOption('3')
  await page.getByLabel('Dépenseur').press('Tab')
  await page.getByLabel('a dépensé').fill('2200')
  await page.getByLabel('a dépensé').press('Enter')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Enzo').check()
  await page.getByLabel('Dépenseur').selectOption('2')
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').click({
    clickCount: 4
  })
  await page.getByLabel('a dépensé').fill('3000')
  await page.getByLabel('Enzo').uncheck()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('0')
  await page.getByLabel('Bob').uncheck()
  await page.getByLabel('Enzo').check()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('450')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('1')
  await page.getByLabel('Bob').check()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('340')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Sarah').check()
  await page.getByLabel('Julien').uncheck()
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').fill('500')
  await page.getByLabel('Dépenseur').selectOption('7')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('5')
  await page.getByLabel('Julien').check()
  await page.getByLabel('Enzo').uncheck()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('400')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('6')
  await page.getByLabel('Sophie').uncheck()
  await page.getByLabel('Oscar').uncheck()
  await page.getByLabel('Julien').uncheck()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('550')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('5')
  await page.getByLabel('Enzo').check()
  await page.getByLabel('Sophie').check()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('120')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('4')
  await page.getByLabel('Oscar').check()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('180')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('1')
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('240')
  await page.getByLabel('Julien').check()
  await page.getByLabel('Enzo').uncheck()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('4')
  await page.getByLabel('Dieudonné').uncheck()
  await page.locator('label').filter({ hasText: 'Nicolas' }).click()
  await page.getByLabel('Sarah').uncheck()
  await page.locator('label').filter({ hasText: 'Sophie' }).click()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('2400')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('0')
  await page.getByLabel('a dépensé').click()
  await page.locator('label').filter({ hasText: 'Enzo' }).click()
  await page.getByLabel('Sarah').check()
  await page.getByLabel('Oscar').uncheck()
  await page.getByLabel('Sophie').check()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('1900')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dieudonné').check()
  await page.getByLabel('a dépensé').click()
  await page
    .locator('div')
    .filter({ hasText: 'DépenseurJulienOscarSophieJulieBobEnzoSarahNicolasDieudonné' })
    .nth(3)
    .click()
  await page.getByLabel('Dépenseur').selectOption('8')
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').fill('660')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('7')
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('400')
  await page.getByLabel('Oscar').check()
  await page.getByLabel('Julien').uncheck()
  await page.getByLabel('Nicolas').check()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('4')
  await page.getByLabel('Julien').check()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('900')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('8')
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('500')
  await page.getByLabel('Julien').uncheck()
  await page.getByLabel('Julie', { exact: true }).uncheck()
  await page.getByLabel('Enzo').uncheck()
  await page.getByLabel('Sarah').uncheck()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
})

test('test rapide', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('checkbox').click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('textbox').nth(1).click({
    clickCount: 3
  })
  await page.getByRole('textbox').nth(1).fill('NIRINA')

  await page.getByLabel('Dépenseur').selectOption('NIRINA')
  await page.getByRole('checkbox', { name: 'Un castor affairé' }).click()
  await page.getByRole('checkbox', { name: 'NIRINA' }).click()
  await page.getByRole('checkbox', { name: 'Un ornithorynque malicieux' }).click()
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').press('ArrowLeft')
  await page.getByLabel('a dépensé').fill('310')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('Un ornithorynque malicieux')
  await page.getByLabel('a dépensé').dblclick()
  await page.getByLabel('a dépensé').press('ControlOrMeta+a')
  await page.getByLabel('a dépensé').fill('218')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()

  await expect(page.getByTitle('Remboursements').getByRole('row').nth(1)).toHaveText(
    'Un castor affairé134€NIRINA'
  )
  await expect(page.getByTitle('Remboursements').getByRole('row').nth(2)).toHaveText(
    'Un castor affairé42€Un ornithorynque malicieux'
  )
  await expect(
    page.getByText(
      'NIRINA a dépensé 310€ pour Un castor affairé, NIRINA, Un ornithorynque malicieux'
    )
  ).toBeVisible()

  await expect(
    page.getByText(
      'Un ornithorynque malicieux a dépensé 218€ pour Un castor affairé, NIRINA, Un ornithorynque malicieux'
    )
  ).toBeVisible()
})

test('test utilisateur', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('checkbox').click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('')
  await page
    .getByText('DépenseurUn castor affairéUne autruche curieuseUn ornithorynque malicieux a dé')
    .click()
  await page.getByLabel('Une autruche curieuse').check()
  await page.getByLabel('Un ornithorynque malicieux').check()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('34')
  await page
    .getByText('DépenseurUn castor affairéUne autruche curieuseUn ornithorynque malicieux a dé')
    .click()
  await page.locator('label').filter({ hasText: 'Un castor affairé' }).click()
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('a dépensé').click()
  await page.getByLabel('a dépensé').fill('34.9')
  await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  await page.getByLabel('Dépenseur').selectOption('1')
  await page.getByLabel('Dépenseur').selectOption('2')
  await page.getByLabel('Dépenseur').selectOption('1')
})

test('test extrême', async ({ page }) => {
  test.slow()
  test.setTimeout(180000)
  await page.goto('/')
  await page.getByRole('checkbox').click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('button', { name: 'Ajouter une personne' }).click()
  await page.getByRole('cell', { name: 'Nom Un castor affairé' }).getByLabel('Nom').click({
    clickCount: 3
  })
  await page.getByRole('cell', { name: 'Nom Un castor affairé' }).getByLabel('Nom').fill('Julien')
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').dblclick()
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').dblclick()
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').click({
    clickCount: 3
  })
  await page.getByRole('row', { name: 'Nom Une autruche curieuse' }).getByLabel('Nom').fill('Oscar')
  await page.getByRole('row', { name: 'Nom Un ornithorynque' }).getByLabel('Nom').click()
  await page
    .getByRole('row', { name: 'Nom Un ornithorynque' })
    .getByLabel('Nom')
    .press('ControlOrMeta+a')
  await page.getByRole('row', { name: 'Nom Un ornithorynque' }).getByLabel('Nom').fill('Sophie')
  await page.getByRole('row', { name: 'Nom Un paresseux rêveur' }).getByLabel('Nom').click()
  await page.getByRole('row', { name: 'Nom Un paresseux rêveur' }).getByLabel('Nom').click({
    clickCount: 3
  })
  await page.getByRole('row', { name: 'Nom Un paresseux rêveur' }).getByLabel('Nom').fill('Julie')
  await page.getByRole('cell', { name: 'Nom Un koala gourmand' }).getByLabel('Nom').fill('Bob')
  await page.getByRole('cell', { name: 'Nom Un panda joueur' }).getByLabel('Nom').fill('Enzo')
  await page.getByRole('cell', { name: 'Nom Un loup solitaire' }).getByLabel('Nom').fill('Sarah')
  await page.getByRole('cell', { name: 'Nom Un renard rusé' }).getByLabel('Nom').fill('Ni')
  await page.getByRole('cell', { name: 'Nom Ni' }).getByLabel('Nom').fill('Nicolas')
  await page.getByRole('cell', { name: 'Nom Ni' }).getByLabel('Nom').press('Tab')
  await page
    .getByRole('cell', { name: 'Nom Un chat malicieux' })
    .getByLabel('Nom')
    .fill('Dieudonné')
  for (let i = 0; i < 10; i++) {
    await page.getByLabel('Dépenseur').selectOption('1')
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('3200')
    await page.getByLabel('a dépensé').press('Tab')
    await page.getByLabel('Julien').check()
    await page.getByLabel('Julien').press('Tab')
    await page.getByLabel('Oscar').check()
    await page.getByLabel('Oscar').press('Tab')
    await page.getByLabel('Sophie').check()
    await page.getByLabel('Sophie').press('Tab')
    await page.getByLabel('Julie', { exact: true }).check()
    await page.getByLabel('Julie', { exact: true }).press('Tab')
    await page.getByLabel('Bob').check()
    await page.getByLabel('Bob').press('Tab')
    await page.getByLabel('Enzo').check()
    await page.getByLabel('Enzo').press('Tab')
    await page.getByLabel('Sarah').check()
    await page.getByLabel('Sarah').press('Tab')
    await page.getByLabel('Nicolas').check()
    await page.getByLabel('Nicolas').press('Tab')
    await page.getByLabel('Dieudonné').check()
    await page.getByLabel('Dieudonné').press('Tab')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByRole('button', { name: 'Ajouter une dépense' }).press('Shift+Tab')
    await page.getByLabel('Dieudonné').press('Shift+Tab')
    await page.getByLabel('Nicolas').press('Shift+Tab')
    await page.getByLabel('Sarah').uncheck()
    await page.getByLabel('Sarah').press('Shift+Tab')
    await page.getByLabel('Enzo').uncheck()
    await page.getByLabel('Dépenseur').selectOption('3')
    await page.getByLabel('Dépenseur').press('Tab')
    await page.getByLabel('a dépensé').fill('2200')
    await page.getByLabel('a dépensé').press('Enter')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Enzo').check()
    await page.getByLabel('Dépenseur').selectOption('2')
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').dblclick()
    await page.getByLabel('a dépensé').click({
      clickCount: 4
    })
    await page.getByLabel('a dépensé').fill('3000')
    await page.getByLabel('Enzo').uncheck()
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('0')
    await page.getByLabel('Bob').uncheck()
    await page.getByLabel('Enzo').check()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').dblclick()
    await page.getByLabel('a dépensé').press('ControlOrMeta+a')
    await page.getByLabel('a dépensé').fill('450')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('1')
    await page.getByLabel('Bob').check()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').dblclick()
    await page.getByLabel('a dépensé').press('ControlOrMeta+a')
    await page.getByLabel('a dépensé').fill('340')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Sarah').check()
    await page.getByLabel('Julien').uncheck()
    await page.getByLabel('a dépensé').dblclick()
    await page.getByLabel('a dépensé').fill('500')
    await page.getByLabel('Dépenseur').selectOption('7')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('5')
    await page.getByLabel('Julien').check()
    await page.getByLabel('Enzo').uncheck()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').dblclick()
    await page.getByLabel('a dépensé').press('ControlOrMeta+a')
    await page.getByLabel('a dépensé').fill('400')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('6')
    await page.getByLabel('Sophie').uncheck()
    await page.getByLabel('Oscar').uncheck()
    await page.getByLabel('Julien').uncheck()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').press('ControlOrMeta+a')
    await page.getByLabel('a dépensé').fill('550')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('5')
    await page.getByLabel('Enzo').check()
    await page.getByLabel('Sophie').check()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').press('ControlOrMeta+a')
    await page.getByLabel('a dépensé').fill('120')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('4')
    await page.getByLabel('Oscar').check()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').press('ControlOrMeta+a')
    await page.getByLabel('a dépensé').fill('180')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('1')
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('240')
    await page.getByLabel('Julien').check()
    await page.getByLabel('Enzo').uncheck()
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('4')
    await page.getByLabel('Dieudonné').uncheck()
    await page.locator('label').filter({ hasText: 'Nicolas' }).click()
    await page.getByLabel('Sarah').uncheck()
    await page.locator('label').filter({ hasText: 'Sophie' }).click()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('2400')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('0')
    await page.getByLabel('a dépensé').click()
    await page.locator('label').filter({ hasText: 'Enzo' }).click()
    await page.getByLabel('Sarah').check()
    await page.getByLabel('Oscar').uncheck()
    await page.getByLabel('Sophie').check()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('1900')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dieudonné').check()
    await page.getByLabel('a dépensé').click()
    await page
      .locator('div')
      .filter({ hasText: 'DépenseurJulienOscarSophieJulieBobEnzoSarahNicolasDieudonné' })
      .nth(3)
      .click()
    await page.getByLabel('Dépenseur').selectOption('8')
    await page.getByLabel('a dépensé').dblclick()
    await page.getByLabel('a dépensé').fill('660')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('7')
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('400')
    await page.getByLabel('Oscar').check()
    await page.getByLabel('Julien').uncheck()
    await page.getByLabel('Nicolas').check()
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('4')
    await page.getByLabel('Julien').check()
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('900')
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
    await page.getByLabel('Dépenseur').selectOption('8')
    await page.getByLabel('a dépensé').click()
    await page.getByLabel('a dépensé').fill('500')
    await page.getByLabel('Julien').uncheck()
    await page.getByLabel('Julie', { exact: true }).uncheck()
    await page.getByLabel('Enzo').uncheck()
    await page.getByLabel('Sarah').uncheck()
    await page.getByRole('button', { name: 'Ajouter une dépense' }).click()
  }
})
