export const MISTRAL_API_KEY = 'MISTRAL_API_KEY'
export const ENABLE_CHAT = 'ENABLE_CHAT'
export const MISTRAL_API_ENDPOINT_KEY = 'MISTRAL_API_ENDPOINT'
export const MISTRAL_AGENT_ID_KEY = 'MISTRAL_AGENT_ID'
