[project]
name = "ia-prompt-engineering-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mistralai>=1.6.0",
    "openai>=1.68.2",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "tenacity>=9.0.0",
]
