name: cd-bonne-energie-bons-voisins
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cd-bonne-energie.yaml
      - apps/bonne-energie-bons-voisins/**
      - packages/layer-bons-comptes/**

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy-bonne-energie-bons-voisins:
    environment: Production – bonne-energie-bons-voisins
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 11
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.10.0
      - name: Use Node.js 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo

      - name: Pull vercel environments
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy bons comptes bons amis
        run: npx turbo-ignore -d ./apps/bonne-energie-bons-voisins || vercel deploy --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
