name: cd-interruptions-simulateur
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cd-interruptions-simulateur.yaml
      - apps/interruptions-simulateur/**
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy-interruptions-simulateur:
    environment: Production – interruptions-simulateur
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 10.18.2
      - name: Use Node.js 20
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install --ignore-scripts

      - run: turbo build --filter=@nirina/interruptions-simulateur
      - name: Deploy simulateur interruptions to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/interruptions-simulateur/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_INTERRUPTEUR_SIDE_ID }}
        timeout-minutes: 1
