name: cd-nirina-site
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cd-site.yaml
      - apps/nirina-site/**
  repository_dispatch:
    types: [blog_update]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy-site:
    environment: Production – blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.6.2
      - name: Use Node.js 20
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache Astro build
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: apps/nirina-site/node_modules/.astro
          key: ${{ runner.os }}-astro-

      - run: pnpm install --ignore-scripts

      - name: set deploy key to pull content
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          ./pull-blog-content.sh
        working-directory: ./apps/nirina-site
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
          COMMIT_MESSAE: ${{ github.event.head_commit.message }}
        run: |
          pnpm install -g netlify-cli@17.37.2 turbo
          netlify deploy --filter nirina-site --build --prod --message "$COMMIT_MESSAGE"
